//
// Created by Derek Witt on 12/7/20.
//

#ifndef AOC_2020_DAY_07_INPUT_H
#define AOC_2020_DAY_07_INPUT_H
#include <string_view>

constexpr std::string_view day_07_data = "faded plum bags contain 5 wavy cyan bags.\n"
                                        "dull aqua bags contain 4 dark fuchsia bags, 1 shiny purple bag.\n"
                                        "dotted olive bags contain 1 striped gray bag.\n"
                                        "vibrant brown bags contain 4 dark tan bags, 4 mirrored gray bags.\n"
                                        "shiny black bags contain 3 mirrored black bags.\n"
                                        "dull bronze bags contain 2 plaid aqua bags, 4 shiny magenta bags, 2 faded green bags, 3 dotted gold bags.\n"
                                        "wavy plum bags contain 5 dim indigo bags.\n"
                                        "drab brown bags contain 5 clear fuchsia bags.\n"
                                        "vibrant maroon bags contain 3 shiny coral bags, 1 dim indigo bag, 4 muted crimson bags, 5 clear black bags.\n"
                                        "posh magenta bags contain no other bags.\n"
                                        "dull brown bags contain 3 dim violet bags, 3 striped silver bags, 1 shiny purple bag.\n"
                                        "pale gray bags contain 3 plaid magenta bags, 3 clear teal bags, 3 pale white bags.\n"
                                        "plaid turquoise bags contain 4 bright orange bags, 5 drab white bags, 4 dotted coral bags.\n"
                                        "dotted silver bags contain 2 pale silver bags, 4 dark teal bags, 5 posh gold bags, 1 bright orange bag.\n"
                                        "light red bags contain 1 dark violet bag, 1 mirrored coral bag, 3 drab tan bags, 4 muted olive bags.\n"
                                        "shiny brown bags contain 5 vibrant lavender bags, 4 dark lavender bags.\n"
                                        "plaid plum bags contain 1 faded green bag.\n"
                                        "vibrant lavender bags contain 4 bright chartreuse bags, 3 dark teal bags, 4 muted aqua bags.\n"
                                        "muted yellow bags contain 5 posh yellow bags, 3 dim olive bags, 1 light cyan bag, 1 plaid gray bag.\n"
                                        "light beige bags contain 2 wavy orange bags, 5 vibrant salmon bags, 2 dim brown bags.\n"
                                        "muted indigo bags contain 3 dim brown bags, 3 drab brown bags.\n"
                                        "dim bronze bags contain 4 dim black bags, 5 wavy turquoise bags, 5 bright violet bags, 2 dark bronze bags.\n"
                                        "shiny teal bags contain 5 plaid chartreuse bags.\n"
                                        "pale aqua bags contain 2 striped lime bags, 4 dark turquoise bags, 3 dull tomato bags, 2 mirrored lavender bags.\n"
                                        "plaid violet bags contain 2 light olive bags.\n"
                                        "dotted maroon bags contain 5 striped maroon bags, 2 shiny turquoise bags, 2 dull gold bags, 4 pale olive bags.\n"
                                        "dim chartreuse bags contain 5 striped plum bags.\n"
                                        "plaid gold bags contain 1 striped green bag, 3 plaid coral bags, 4 dotted violet bags.\n"
                                        "faded tomato bags contain 2 dark indigo bags.\n"
                                        "posh plum bags contain 1 wavy chartreuse bag, 4 vibrant blue bags.\n"
                                        "drab bronze bags contain 2 mirrored gray bags, 3 vibrant plum bags.\n"
                                        "muted blue bags contain 1 bright brown bag, 2 pale coral bags, 5 plaid purple bags, 4 dim lavender bags.\n"
                                        "striped indigo bags contain 5 dark salmon bags.\n"
                                        "shiny tan bags contain 2 faded bronze bags, 3 mirrored lavender bags, 2 mirrored cyan bags.\n"
                                        "dim red bags contain 5 dull salmon bags, 3 dim purple bags, 2 striped crimson bags.\n"
                                        "plaid gray bags contain 5 bright violet bags, 4 vibrant aqua bags, 4 dull tomato bags.\n"
                                        "dotted white bags contain 1 drab brown bag, 5 light brown bags.\n"
                                        "plaid tan bags contain 3 striped teal bags, 2 dotted brown bags.\n"
                                        "vibrant black bags contain 3 plaid tan bags, 4 muted white bags, 4 drab orange bags, 5 muted aqua bags.\n"
                                        "drab purple bags contain 5 muted violet bags, 2 vibrant blue bags, 4 pale olive bags.\n"
                                        "mirrored beige bags contain 1 plaid gray bag, 2 mirrored lime bags, 3 dark brown bags.\n"
                                        "vibrant olive bags contain 5 shiny indigo bags.\n"
                                        "drab green bags contain 1 muted violet bag.\n"
                                        "faded turquoise bags contain 2 striped brown bags, 3 vibrant white bags, 1 dull lavender bag, 5 bright olive bags.\n"
                                        "shiny maroon bags contain 1 dim bronze bag.\n"
                                        "dull white bags contain 1 muted salmon bag, 4 dim olive bags, 5 drab white bags, 1 dotted teal bag.\n"
                                        "dim white bags contain 3 mirrored lavender bags.\n"
                                        "clear beige bags contain 5 shiny cyan bags, 3 clear chartreuse bags.\n"
                                        "plaid tomato bags contain 5 muted beige bags.\n"
                                        "bright teal bags contain 5 shiny gold bags, 4 clear beige bags, 5 vibrant chartreuse bags.\n"
                                        "dotted salmon bags contain 1 clear fuchsia bag, 2 muted maroon bags, 4 posh yellow bags, 1 drab chartreuse bag.\n"
                                        "light gold bags contain 4 light maroon bags.\n"
                                        "faded cyan bags contain 2 posh magenta bags, 2 dark violet bags.\n"
                                        "drab cyan bags contain 5 faded purple bags, 4 striped crimson bags, 1 shiny maroon bag, 4 drab tomato bags.\n"
                                        "dotted black bags contain 3 striped turquoise bags, 4 dark tan bags, 4 vibrant lavender bags.\n"
                                        "faded purple bags contain 4 dull purple bags.\n"
                                        "dim violet bags contain 2 clear blue bags.\n"
                                        "wavy gray bags contain 4 muted crimson bags, 2 mirrored silver bags, 5 vibrant chartreuse bags.\n"
                                        "posh tan bags contain 4 drab tan bags, 3 muted crimson bags, 2 striped crimson bags, 2 plaid fuchsia bags.\n"
                                        "mirrored magenta bags contain 5 pale bronze bags.\n"
                                        "plaid brown bags contain 1 bright chartreuse bag.\n"
                                        "drab orange bags contain 4 drab teal bags, 1 dark bronze bag, 2 clear purple bags.\n"
                                        "dim green bags contain 5 dull maroon bags, 1 dull green bag.\n"
                                        "faded teal bags contain 2 bright yellow bags, 2 posh red bags, 2 posh indigo bags.\n"
                                        "dim gray bags contain 4 wavy blue bags, 2 shiny maroon bags, 1 pale cyan bag.\n"
                                        "light crimson bags contain 1 wavy plum bag, 3 muted magenta bags, 3 plaid aqua bags, 2 striped chartreuse bags.\n"
                                        "clear white bags contain 2 posh magenta bags, 5 bright white bags, 5 drab bronze bags, 3 vibrant beige bags.\n"
                                        "drab magenta bags contain 4 pale olive bags.\n"
                                        "plaid silver bags contain 4 bright violet bags, 3 dim brown bags, 1 dark teal bag.\n"
                                        "bright bronze bags contain 4 posh white bags, 3 dull salmon bags.\n"
                                        "drab maroon bags contain 3 clear black bags, 2 dotted orange bags.\n"
                                        "dark fuchsia bags contain 3 faded chartreuse bags, 5 clear green bags, 4 bright brown bags.\n"
                                        "vibrant salmon bags contain 1 bright red bag, 5 clear black bags, 2 clear green bags.\n"
                                        "shiny crimson bags contain 4 muted fuchsia bags, 2 plaid red bags, 3 clear green bags.\n"
                                        "plaid crimson bags contain 4 bright gold bags, 2 clear turquoise bags, 3 faded magenta bags.\n"
                                        "dim turquoise bags contain 3 drab brown bags, 5 plaid cyan bags, 3 plaid teal bags, 5 shiny silver bags.\n"
                                        "clear crimson bags contain 3 plaid blue bags, 2 drab tomato bags, 2 dull cyan bags, 3 mirrored fuchsia bags.\n"
                                        "pale tomato bags contain 1 dull yellow bag, 3 muted aqua bags.\n"
                                        "dim orange bags contain 1 posh magenta bag, 2 wavy gray bags, 5 faded indigo bags.\n"
                                        "mirrored orange bags contain 1 posh bronze bag, 2 faded white bags, 1 light orange bag, 2 posh red bags.\n"
                                        "striped turquoise bags contain 5 muted salmon bags, 5 dark white bags, 1 mirrored purple bag, 3 pale chartreuse bags.\n"
                                        "dotted coral bags contain 3 bright brown bags, 2 posh yellow bags, 3 drab maroon bags.\n"
                                        "wavy maroon bags contain 2 clear lime bags.\n"
                                        "mirrored indigo bags contain 1 mirrored cyan bag, 1 posh plum bag, 2 plaid silver bags.\n"
                                        "wavy indigo bags contain 5 dark violet bags, 5 drab black bags, 4 dark orange bags, 5 muted green bags.\n"
                                        "striped tomato bags contain 4 dark indigo bags, 5 light lavender bags.\n"
                                        "pale lime bags contain 2 bright orange bags.\n"
                                        "muted maroon bags contain 2 bright violet bags, 1 shiny coral bag, 1 posh gray bag.\n"
                                        "drab lavender bags contain 1 muted magenta bag.\n"
                                        "bright fuchsia bags contain 1 striped lime bag.\n"
                                        "wavy beige bags contain 2 bright brown bags, 1 pale black bag, 1 drab tomato bag, 4 vibrant blue bags.\n"
                                        "shiny olive bags contain 2 dim teal bags, 1 mirrored cyan bag, 4 dim yellow bags, 4 muted aqua bags.\n"
                                        "posh coral bags contain no other bags.\n"
                                        "dark green bags contain 2 posh brown bags, 2 muted white bags, 4 bright fuchsia bags.\n"
                                        "shiny green bags contain 1 faded crimson bag, 3 striped purple bags, 4 shiny salmon bags, 2 dark bronze bags.\n"
                                        "clear coral bags contain no other bags.\n"
                                        "dull salmon bags contain 1 muted white bag.\n"
                                        "dark lavender bags contain 2 plaid gray bags, 4 muted olive bags.\n"
                                        "bright silver bags contain 5 pale black bags.\n"
                                        "posh green bags contain 5 muted olive bags, 4 dotted crimson bags, 4 dotted brown bags.\n"
                                        "dotted fuchsia bags contain 5 shiny chartreuse bags, 1 dotted coral bag, 1 shiny cyan bag.\n"
                                        "dim fuchsia bags contain 1 striped orange bag, 1 clear crimson bag.\n"
                                        "dotted cyan bags contain 5 muted olive bags, 3 shiny white bags.\n"
                                        "dark beige bags contain 4 light teal bags, 4 drab teal bags, 5 wavy beige bags.\n"
                                        "striped magenta bags contain 5 plaid purple bags, 3 dotted crimson bags, 2 dull tomato bags.\n"
                                        "striped blue bags contain 3 dim aqua bags.\n"
                                        "light silver bags contain 3 shiny green bags, 2 vibrant black bags, 1 wavy turquoise bag, 3 faded bronze bags.\n"
                                        "pale indigo bags contain 4 pale silver bags, 3 dotted tomato bags, 1 dark violet bag, 3 clear lime bags.\n"
                                        "mirrored turquoise bags contain 1 pale salmon bag, 2 dotted crimson bags, 1 drab tomato bag, 2 muted green bags.\n"
                                        "striped beige bags contain 3 dotted tomato bags, 4 vibrant purple bags, 2 plaid tomato bags, 4 dark salmon bags.\n"
                                        "pale silver bags contain 5 dark lavender bags, 4 drab tan bags, 5 clear yellow bags.\n"
                                        "dark lime bags contain 3 pale aqua bags, 5 posh green bags.\n"
                                        "faded coral bags contain 3 dull tomato bags, 4 dark bronze bags, 3 drab tomato bags, 2 bright white bags.\n"
                                        "mirrored lavender bags contain 3 mirrored cyan bags.\n"
                                        "bright crimson bags contain 2 mirrored silver bags.\n"
                                        "striped gray bags contain 3 dotted coral bags, 4 muted maroon bags, 4 dark teal bags, 5 pale bronze bags.\n"
                                        "dotted magenta bags contain 2 dim teal bags, 2 wavy turquoise bags, 5 dull turquoise bags.\n"
                                        "posh white bags contain 4 drab tomato bags, 2 muted aqua bags.\n"
                                        "striped red bags contain 2 plaid blue bags, 1 light plum bag, 3 bright white bags.\n"
                                        "pale white bags contain 1 light purple bag.\n"
                                        "shiny coral bags contain no other bags.\n"
                                        "dark magenta bags contain 4 pale tan bags, 1 posh chartreuse bag, 2 pale yellow bags, 2 pale indigo bags.\n"
                                        "light gray bags contain 4 pale green bags, 5 dotted green bags, 4 shiny gray bags.\n"
                                        "dim gold bags contain 3 clear violet bags, 5 plaid aqua bags, 2 bright tomato bags, 2 wavy teal bags.\n"
                                        "dim crimson bags contain 4 muted blue bags, 2 light tan bags.\n"
                                        "wavy tan bags contain 1 posh plum bag, 3 mirrored gray bags, 1 muted purple bag.\n"
                                        "posh brown bags contain 4 mirrored black bags.\n"
                                        "bright plum bags contain 3 vibrant plum bags, 3 mirrored crimson bags.\n"
                                        "faded black bags contain 1 pale lime bag, 2 pale tomato bags.\n"
                                        "mirrored yellow bags contain 1 pale aqua bag, 4 dull aqua bags, 4 shiny white bags, 3 clear lime bags.\n"
                                        "muted tan bags contain 2 clear brown bags.\n"
                                        "drab white bags contain 5 dull coral bags, 2 drab green bags, 4 wavy tomato bags, 5 mirrored cyan bags.\n"
                                        "dull black bags contain 4 vibrant tan bags, 1 shiny chartreuse bag, 5 pale gold bags.\n"
                                        "posh maroon bags contain 5 dark coral bags, 5 faded yellow bags, 2 light lavender bags, 2 wavy teal bags.\n"
                                        "drab coral bags contain 4 posh chartreuse bags, 2 dim red bags.\n"
                                        "posh indigo bags contain 2 plaid brown bags, 4 muted green bags.\n"
                                        "drab aqua bags contain 2 pale magenta bags, 2 posh orange bags.\n"
                                        "drab crimson bags contain 2 pale bronze bags, 4 dotted blue bags, 2 dim silver bags.\n"
                                        "drab silver bags contain 5 clear blue bags, 4 pale bronze bags.\n"
                                        "clear salmon bags contain 2 pale aqua bags, 1 plaid gray bag, 1 clear coral bag.\n"
                                        "wavy chartreuse bags contain no other bags.\n"
                                        "dull plum bags contain 3 plaid gray bags, 3 plaid aqua bags, 2 mirrored beige bags, 2 wavy magenta bags.\n"
                                        "faded gray bags contain 2 dull cyan bags, 3 light lime bags, 3 bright lavender bags, 5 wavy plum bags.\n"
                                        "striped teal bags contain 4 drab maroon bags.\n"
                                        "clear lavender bags contain 3 clear coral bags, 5 bright crimson bags, 5 drab brown bags, 2 dim indigo bags.\n"
                                        "mirrored maroon bags contain 1 clear gray bag, 3 shiny salmon bags, 3 mirrored violet bags.\n"
                                        "muted turquoise bags contain 2 drab teal bags, 2 plaid plum bags, 4 plaid coral bags, 2 wavy chartreuse bags.\n"
                                        "dark white bags contain 4 bright fuchsia bags, 1 dull white bag, 3 shiny indigo bags, 3 dim white bags.\n"
                                        "drab red bags contain 3 dotted teal bags, 2 striped purple bags.\n"
                                        "muted teal bags contain 3 dark violet bags, 4 plaid chartreuse bags, 2 pale crimson bags.\n"
                                        "wavy red bags contain 2 clear crimson bags.\n"
                                        "striped olive bags contain 2 mirrored lavender bags.\n"
                                        "dull teal bags contain 4 pale teal bags, 5 pale violet bags, 2 drab white bags.\n"
                                        "light black bags contain 1 dark red bag, 2 plaid tan bags.\n"
                                        "clear orange bags contain 5 bright cyan bags.\n"
                                        "pale yellow bags contain 2 bright lavender bags.\n"
                                        "posh cyan bags contain 4 clear coral bags.\n"
                                        "drab tomato bags contain 4 vibrant blue bags, 5 faded beige bags, 3 clear coral bags, 2 mirrored white bags.\n"
                                        "pale orange bags contain 2 light aqua bags.\n"
                                        "dull tomato bags contain 5 plaid aqua bags, 2 posh magenta bags, 3 vibrant aqua bags.\n"
                                        "pale turquoise bags contain 1 pale coral bag, 3 dim teal bags.\n"
                                        "plaid maroon bags contain 5 posh maroon bags.\n"
                                        "vibrant beige bags contain 5 dull coral bags.\n"
                                        "bright purple bags contain 2 vibrant salmon bags, 5 dotted purple bags, 5 clear silver bags.\n"
                                        "dull coral bags contain 4 vibrant aqua bags, 3 dotted brown bags, 4 shiny coral bags.\n"
                                        "drab gray bags contain 4 vibrant lavender bags.\n"
                                        "dull lavender bags contain 3 vibrant lavender bags, 1 posh red bag, 4 drab tan bags, 3 light purple bags.\n"
                                        "striped maroon bags contain 3 bright silver bags.\n"
                                        "mirrored silver bags contain 5 clear blue bags, 3 posh magenta bags, 2 bright brown bags.\n"
                                        "faded yellow bags contain 2 muted maroon bags.\n"
                                        "striped purple bags contain 2 dotted yellow bags, 1 clear cyan bag, 2 dark teal bags.\n"
                                        "clear gray bags contain 5 dim black bags, 1 faded green bag, 5 muted crimson bags.\n"
                                        "plaid cyan bags contain 2 dark teal bags, 1 pale lime bag, 1 wavy beige bag.\n"
                                        "bright orange bags contain 5 mirrored brown bags, 2 dotted gold bags.\n"
                                        "dotted turquoise bags contain 3 plaid gray bags, 3 clear chartreuse bags.\n"
                                        "vibrant turquoise bags contain 1 muted brown bag, 3 dim purple bags, 1 posh gray bag, 5 pale bronze bags.\n"
                                        "striped lime bags contain 1 shiny gold bag.\n"
                                        "light violet bags contain 4 mirrored purple bags, 5 clear blue bags.\n"
                                        "striped orange bags contain 3 light gold bags, 3 light olive bags, 3 muted crimson bags, 2 pale cyan bags.\n"
                                        "drab turquoise bags contain 3 dim magenta bags, 4 pale black bags.\n"
                                        "pale salmon bags contain 2 mirrored cyan bags, 4 vibrant blue bags.\n"
                                        "shiny yellow bags contain 5 vibrant tomato bags, 3 muted salmon bags, 5 wavy tomato bags.\n"
                                        "plaid lime bags contain 2 pale yellow bags, 2 shiny red bags, 3 muted crimson bags, 4 dull green bags.\n"
                                        "muted cyan bags contain 4 bright green bags, 5 striped bronze bags, 1 vibrant lavender bag, 4 posh violet bags.\n"
                                        "dull cyan bags contain 5 dark lavender bags, 5 drab green bags, 1 bright crimson bag, 4 mirrored silver bags.\n"
                                        "pale beige bags contain 3 posh coral bags.\n"
                                        "shiny chartreuse bags contain 4 mirrored silver bags.\n"
                                        "dark silver bags contain 2 dull turquoise bags, 1 muted maroon bag, 5 vibrant magenta bags.\n"
                                        "mirrored violet bags contain 4 dark brown bags.\n"
                                        "clear aqua bags contain 2 striped beige bags, 1 dotted indigo bag, 5 faded violet bags, 5 vibrant violet bags.\n"
                                        "plaid teal bags contain 3 mirrored lavender bags, 4 posh gray bags.\n"
                                        "wavy olive bags contain 3 dull blue bags, 5 bright salmon bags, 5 shiny purple bags.\n"
                                        "pale lavender bags contain 4 light purple bags, 2 dotted gray bags, 2 pale plum bags, 3 shiny silver bags.\n"
                                        "shiny blue bags contain 2 vibrant white bags, 3 light gold bags, 3 mirrored lavender bags, 1 drab plum bag.\n"
                                        "light coral bags contain 4 light teal bags, 1 striped chartreuse bag, 5 dotted chartreuse bags.\n"
                                        "pale brown bags contain 2 dim gold bags, 2 clear turquoise bags, 3 bright cyan bags, 4 clear maroon bags.\n"
                                        "vibrant tomato bags contain 3 dark brown bags, 1 vibrant blue bag.\n"
                                        "dull olive bags contain 5 mirrored yellow bags, 2 shiny cyan bags.\n"
                                        "light chartreuse bags contain 2 dull aqua bags, 4 dull brown bags, 1 clear fuchsia bag, 4 bright yellow bags.\n"
                                        "posh gray bags contain 4 posh green bags, 1 mirrored gray bag.\n"
                                        "bright yellow bags contain 4 pale aqua bags.\n"
                                        "bright gold bags contain 3 pale indigo bags, 3 dull crimson bags.\n"
                                        "dotted red bags contain 4 pale turquoise bags, 4 muted blue bags, 1 bright bronze bag, 2 light blue bags.\n"
                                        "clear brown bags contain 1 mirrored yellow bag.\n"
                                        "light plum bags contain 2 bright violet bags.\n"
                                        "dim purple bags contain 3 faded chartreuse bags, 5 light teal bags.\n"
                                        "dull yellow bags contain 5 muted aqua bags, 3 dotted coral bags, 2 drab maroon bags.\n"
                                        "shiny gold bags contain 4 pale black bags, 4 dim violet bags, 3 muted yellow bags.\n"
                                        "mirrored crimson bags contain 1 striped teal bag, 5 mirrored cyan bags.\n"
                                        "shiny lavender bags contain 4 bright brown bags, 3 bright tan bags, 5 dotted crimson bags, 4 pale black bags.\n"
                                        "vibrant cyan bags contain 1 dim yellow bag, 5 bright tan bags.\n"
                                        "wavy gold bags contain 2 dark brown bags, 1 dull yellow bag.\n"
                                        "dark cyan bags contain 4 dim white bags, 2 mirrored indigo bags, 4 muted white bags, 2 bright white bags.\n"
                                        "posh lime bags contain 4 shiny plum bags, 3 plaid fuchsia bags.\n"
                                        "posh purple bags contain 3 muted salmon bags.\n"
                                        "pale magenta bags contain 1 drab gold bag, 1 dark white bag, 3 posh silver bags.\n"
                                        "dim plum bags contain 4 dark chartreuse bags, 4 mirrored lavender bags.\n"
                                        "plaid indigo bags contain 2 clear lime bags, 5 dull tomato bags.\n"
                                        "dark blue bags contain 1 bright olive bag, 1 dull bronze bag, 1 shiny gold bag.\n"
                                        "dull red bags contain 2 wavy teal bags, 3 wavy crimson bags, 1 faded olive bag.\n"
                                        "striped yellow bags contain 4 drab salmon bags.\n"
                                        "vibrant magenta bags contain 4 light beige bags, 2 dark red bags, 1 plaid magenta bag, 5 dim magenta bags.\n"
                                        "plaid red bags contain 2 striped red bags, 4 light plum bags, 3 mirrored silver bags.\n"
                                        "wavy orange bags contain 5 vibrant white bags, 1 posh coral bag, 5 muted purple bags, 2 light coral bags.\n"
                                        "pale green bags contain 5 pale aqua bags, 1 clear gray bag.\n"
                                        "dotted chartreuse bags contain 4 muted violet bags, 5 striped teal bags.\n"
                                        "light turquoise bags contain 5 dull turquoise bags, 2 dark aqua bags, 1 dull teal bag.\n"
                                        "shiny violet bags contain 2 pale indigo bags.\n"
                                        "light white bags contain 3 mirrored indigo bags, 1 faded blue bag, 1 plaid white bag, 1 posh plum bag.\n"
                                        "muted beige bags contain 4 drab gold bags.\n"
                                        "faded silver bags contain 2 drab white bags, 5 pale white bags, 3 clear lime bags.\n"
                                        "faded red bags contain 1 bright turquoise bag, 5 faded coral bags, 2 drab purple bags, 5 bright olive bags.\n"
                                        "shiny bronze bags contain 4 plaid purple bags, 5 bright red bags, 1 muted white bag, 2 dull fuchsia bags.\n"
                                        "dull gold bags contain 1 dotted orange bag.\n"
                                        "muted olive bags contain 1 clear coral bag, 1 posh magenta bag, 2 bright violet bags, 1 wavy chartreuse bag.\n"
                                        "dotted bronze bags contain 1 plaid beige bag, 3 clear olive bags, 2 light lime bags, 5 dull beige bags.\n"
                                        "shiny orange bags contain 5 pale brown bags, 5 clear tomato bags.\n"
                                        "wavy salmon bags contain 2 shiny maroon bags.\n"
                                        "wavy crimson bags contain 5 bright violet bags, 3 plaid violet bags.\n"
                                        "bright coral bags contain 1 dull bronze bag, 5 dotted gold bags, 1 posh gray bag.\n"
                                        "dotted crimson bags contain 2 posh magenta bags, 4 mirrored white bags.\n"
                                        "bright violet bags contain no other bags.\n"
                                        "drab blue bags contain 5 shiny gold bags, 1 shiny brown bag, 4 dark silver bags.\n"
                                        "posh salmon bags contain 4 dim purple bags, 1 striped lime bag, 1 muted gray bag, 2 drab gold bags.\n"
                                        "dim coral bags contain 3 dark red bags, 2 faded crimson bags.\n"
                                        "dark aqua bags contain 3 dotted salmon bags, 4 pale olive bags, 1 vibrant aqua bag, 5 dull lavender bags.\n"
                                        "dark orange bags contain 4 mirrored teal bags, 5 clear salmon bags.\n"
                                        "vibrant red bags contain 3 vibrant blue bags.\n"
                                        "muted lime bags contain 1 dull silver bag.\n"
                                        "clear tan bags contain 2 striped beige bags, 1 posh coral bag, 1 wavy teal bag, 2 faded plum bags.\n"
                                        "vibrant coral bags contain 2 faded blue bags, 4 bright turquoise bags.\n"
                                        "dark olive bags contain 2 dark indigo bags.\n"
                                        "dotted blue bags contain 5 faded cyan bags, 4 striped aqua bags, 4 dotted gold bags.\n"
                                        "bright maroon bags contain 1 dark bronze bag, 3 vibrant aqua bags, 4 dim magenta bags, 3 clear crimson bags.\n"
                                        "bright cyan bags contain 2 wavy tomato bags.\n"
                                        "plaid olive bags contain 3 striped indigo bags, 5 dim purple bags, 3 striped bronze bags, 2 light teal bags.\n"
                                        "plaid chartreuse bags contain 3 plaid yellow bags, 1 faded brown bag, 1 vibrant tan bag, 4 wavy fuchsia bags.\n"
                                        "dull maroon bags contain 3 muted yellow bags.\n"
                                        "light fuchsia bags contain 5 drab maroon bags, 5 muted silver bags.\n"
                                        "dull orange bags contain 4 dim indigo bags, 4 posh beige bags, 1 bright red bag.\n"
                                        "dull blue bags contain 5 wavy yellow bags, 4 posh gray bags.\n"
                                        "plaid yellow bags contain 1 bright fuchsia bag, 1 faded beige bag, 1 wavy beige bag, 4 light green bags.\n"
                                        "clear black bags contain 1 dull tomato bag.\n"
                                        "muted coral bags contain 5 drab indigo bags.\n"
                                        "plaid magenta bags contain 3 posh salmon bags.\n"
                                        "clear tomato bags contain 5 dotted brown bags, 3 dim tomato bags, 3 drab brown bags.\n"
                                        "clear yellow bags contain 3 clear black bags, 2 mirrored black bags.\n"
                                        "dark gray bags contain 5 light bronze bags, 4 dotted coral bags, 4 dim chartreuse bags.\n"
                                        "light magenta bags contain 4 wavy turquoise bags, 1 mirrored green bag, 2 plaid chartreuse bags.\n"
                                        "shiny indigo bags contain 1 bright silver bag, 2 pale tomato bags, 4 light teal bags, 4 posh coral bags.\n"
                                        "muted gray bags contain 3 faded beige bags, 1 dark teal bag, 3 muted violet bags, 3 muted white bags.\n"
                                        "wavy lavender bags contain 1 clear chartreuse bag, 2 clear maroon bags, 5 dull plum bags.\n"
                                        "faded olive bags contain 4 mirrored yellow bags, 4 vibrant tomato bags, 5 muted olive bags.\n"
                                        "muted crimson bags contain 1 mirrored gray bag, 4 dim violet bags.\n"
                                        "drab chartreuse bags contain 1 pale olive bag, 1 vibrant plum bag.\n"
                                        "wavy cyan bags contain 2 mirrored coral bags.\n"
                                        "mirrored plum bags contain 3 bright turquoise bags, 3 dark beige bags, 4 mirrored beige bags.\n"
                                        "plaid lavender bags contain 1 drab white bag.\n"
                                        "muted gold bags contain 1 clear black bag, 2 light orange bags, 4 dotted red bags, 4 dull silver bags.\n"
                                        "faded bronze bags contain 4 posh plum bags.\n"
                                        "clear turquoise bags contain 1 light gold bag, 1 clear beige bag, 2 striped chartreuse bags.\n"
                                        "vibrant gray bags contain 1 plaid white bag.\n"
                                        "bright tan bags contain 3 drab silver bags, 2 faded yellow bags, 2 bright green bags.\n"
                                        "pale bronze bags contain 5 posh coral bags, 4 clear coral bags, 1 dotted orange bag, 4 wavy chartreuse bags.\n"
                                        "clear plum bags contain 1 dim plum bag, 4 light gold bags.\n"
                                        "posh turquoise bags contain 3 wavy bronze bags, 4 shiny purple bags.\n"
                                        "posh teal bags contain 2 striped magenta bags, 3 dark magenta bags, 5 faded silver bags, 5 mirrored chartreuse bags.\n"
                                        "dim yellow bags contain 4 pale bronze bags, 3 shiny tan bags.\n"
                                        "faded lavender bags contain 3 dull white bags, 3 striped teal bags.\n"
                                        "wavy magenta bags contain 2 pale aqua bags, 4 shiny indigo bags.\n"
                                        "dim brown bags contain 2 bright brown bags, 3 striped chartreuse bags, 5 dull purple bags, 1 light cyan bag.\n"
                                        "light lime bags contain 5 clear crimson bags, 4 plaid indigo bags, 1 pale silver bag.\n"
                                        "striped silver bags contain 3 posh green bags, 3 muted violet bags, 1 drab green bag.\n"
                                        "bright brown bags contain no other bags.\n"
                                        "vibrant fuchsia bags contain 4 dull olive bags, 2 mirrored gold bags, 3 mirrored bronze bags, 1 posh crimson bag.\n"
                                        "plaid purple bags contain 3 faded beige bags, 1 drab green bag, 2 striped chartreuse bags.\n"
                                        "wavy violet bags contain 2 vibrant gray bags, 5 wavy fuchsia bags.\n"
                                        "dark maroon bags contain 5 pale chartreuse bags, 5 striped brown bags.\n"
                                        "pale coral bags contain 3 vibrant plum bags.\n"
                                        "dark black bags contain 4 striped salmon bags, 4 dim bronze bags.\n"
                                        "plaid bronze bags contain 2 mirrored black bags, 1 drab bronze bag, 4 plaid purple bags, 5 dull tomato bags.\n"
                                        "faded orange bags contain 5 plaid indigo bags.\n"
                                        "light lavender bags contain 2 shiny magenta bags, 5 dim lavender bags, 1 dotted crimson bag.\n"
                                        "dull chartreuse bags contain 4 clear lime bags.\n"
                                        "dark gold bags contain 4 light magenta bags.\n"
                                        "dim black bags contain 4 shiny silver bags, 1 dull tomato bag.\n"
                                        "plaid salmon bags contain 3 light magenta bags, 4 dull fuchsia bags, 2 striped salmon bags.\n"
                                        "vibrant bronze bags contain 5 mirrored white bags, 1 dull coral bag.\n"
                                        "wavy brown bags contain 1 light gold bag, 4 drab purple bags, 3 muted violet bags, 4 muted fuchsia bags.\n"
                                        "dotted lavender bags contain 4 dotted indigo bags, 2 dull lavender bags.\n"
                                        "dotted gold bags contain 1 posh magenta bag, 2 posh yellow bags.\n"
                                        "faded brown bags contain 4 muted blue bags, 3 wavy teal bags.\n"
                                        "light yellow bags contain 3 clear black bags, 1 dotted crimson bag.\n"
                                        "striped salmon bags contain 1 dull yellow bag, 5 mirrored gray bags, 5 light lavender bags, 5 mirrored brown bags.\n"
                                        "light blue bags contain 5 mirrored purple bags, 3 dim violet bags, 2 pale tomato bags.\n"
                                        "faded gold bags contain 3 plaid gray bags.\n"
                                        "shiny aqua bags contain 1 striped crimson bag, 5 pale black bags.\n"
                                        "shiny lime bags contain 4 dark green bags.\n"
                                        "vibrant tan bags contain 3 clear silver bags, 3 pale white bags.\n"
                                        "vibrant aqua bags contain no other bags.\n"
                                        "vibrant teal bags contain 3 wavy tan bags.\n"
                                        "light maroon bags contain 3 vibrant silver bags.\n"
                                        "faded crimson bags contain 3 plaid red bags.\n"
                                        "light teal bags contain 2 dark teal bags, 1 faded beige bag, 4 dull cyan bags.\n"
                                        "mirrored coral bags contain 2 vibrant plum bags.\n"
                                        "muted black bags contain 2 drab magenta bags, 1 mirrored gray bag, 4 drab tan bags, 1 dim indigo bag.\n"
                                        "striped gold bags contain 1 dark lavender bag, 4 drab brown bags, 2 bright silver bags, 2 striped teal bags.\n"
                                        "light purple bags contain 3 posh gray bags.\n"
                                        "dull silver bags contain 2 clear chartreuse bags, 3 plaid silver bags, 1 drab salmon bag, 2 wavy teal bags.\n"
                                        "clear bronze bags contain 4 dull red bags.\n"
                                        "wavy yellow bags contain 3 dull tomato bags, 2 posh green bags, 4 plaid aqua bags, 2 faded purple bags.\n"
                                        "muted purple bags contain 5 pale black bags, 2 muted salmon bags, 2 muted yellow bags.\n"
                                        "plaid aqua bags contain no other bags.\n"
                                        "drab plum bags contain 3 drab turquoise bags.\n"
                                        "muted orange bags contain 1 faded blue bag, 5 plaid brown bags, 4 mirrored chartreuse bags.\n"
                                        "dim silver bags contain 4 dark fuchsia bags, 2 clear cyan bags, 2 dark green bags, 4 dotted silver bags.\n"
                                        "pale tan bags contain 5 shiny silver bags, 5 drab indigo bags.\n"
                                        "wavy tomato bags contain 4 clear black bags, 4 plaid gray bags.\n"
                                        "posh bronze bags contain 4 drab green bags.\n"
                                        "clear blue bags contain 3 bright brown bags, 5 dull tomato bags, 1 clear black bag, 5 bright violet bags.\n"
                                        "striped plum bags contain 4 plaid yellow bags, 3 dark teal bags, 2 mirrored lavender bags, 1 dotted salmon bag.\n"
                                        "muted salmon bags contain 1 dull cyan bag, 2 clear coral bags, 1 posh coral bag.\n"
                                        "light aqua bags contain 4 clear maroon bags, 4 striped black bags.\n"
                                        "bright blue bags contain 4 drab violet bags, 4 light indigo bags, 3 muted indigo bags.\n"
                                        "light brown bags contain 5 striped lavender bags.\n"
                                        "light salmon bags contain 1 drab beige bag, 5 faded orange bags, 4 plaid coral bags, 5 light chartreuse bags.\n"
                                        "posh beige bags contain 1 shiny red bag.\n"
                                        "dotted orange bags contain 2 dotted brown bags, 3 mirrored silver bags, 1 dull tomato bag.\n"
                                        "wavy purple bags contain 1 mirrored green bag, 1 clear maroon bag.\n"
                                        "dark coral bags contain 5 bright chartreuse bags, 4 clear lime bags.\n"
                                        "dim lime bags contain 3 bright olive bags, 3 dull gold bags.\n"
                                        "pale plum bags contain 1 light orange bag, 3 drab orange bags, 5 mirrored purple bags.\n"
                                        "dim beige bags contain 5 pale fuchsia bags, 4 mirrored fuchsia bags, 4 plaid teal bags, 1 shiny orange bag.\n"
                                        "drab tan bags contain 5 plaid silver bags, 3 muted crimson bags, 1 clear salmon bag.\n"
                                        "posh blue bags contain 4 plaid aqua bags, 2 drab salmon bags, 4 pale teal bags, 2 drab gold bags.\n"
                                        "drab violet bags contain 3 shiny white bags.\n"
                                        "shiny plum bags contain 3 mirrored green bags, 2 dark yellow bags, 3 pale salmon bags.\n"
                                        "pale fuchsia bags contain 5 faded violet bags.\n"
                                        "clear fuchsia bags contain 2 dark lavender bags, 3 posh green bags.\n"
                                        "mirrored lime bags contain 3 light bronze bags.\n"
                                        "plaid white bags contain 1 dim lavender bag, 4 dim olive bags, 3 clear yellow bags.\n"
                                        "striped violet bags contain 4 plaid plum bags, 3 plaid black bags, 4 pale teal bags, 5 wavy magenta bags.\n"
                                        "dark purple bags contain 2 shiny gold bags, 3 faded blue bags.\n"
                                        "mirrored blue bags contain 1 drab fuchsia bag, 4 posh white bags, 3 wavy red bags.\n"
                                        "pale black bags contain 2 dim olive bags, 5 bright brown bags.\n"
                                        "dark brown bags contain 5 dotted purple bags, 2 striped silver bags.\n"
                                        "muted lavender bags contain 3 posh brown bags, 2 clear yellow bags, 3 posh coral bags, 1 shiny tan bag.\n"
                                        "muted bronze bags contain 1 drab teal bag, 5 drab tomato bags, 1 drab magenta bag, 5 posh maroon bags.\n"
                                        "posh violet bags contain 5 bright white bags, 5 vibrant tan bags.\n"
                                        "clear green bags contain 3 mirrored silver bags, 2 dotted orange bags.\n"
                                        "dotted plum bags contain 3 plaid yellow bags, 1 wavy yellow bag, 1 drab cyan bag.\n"
                                        "drab olive bags contain 1 shiny indigo bag.\n"
                                        "wavy turquoise bags contain 3 muted yellow bags.\n"
                                        "dark violet bags contain 2 bright crimson bags, 4 bright fuchsia bags, 2 dull blue bags.\n"
                                        "posh gold bags contain 3 drab teal bags.\n"
                                        "dim cyan bags contain 5 clear olive bags, 4 bright turquoise bags, 1 pale gray bag.\n"
                                        "posh red bags contain 1 bright salmon bag.\n"
                                        "dull tan bags contain 4 plaid cyan bags.\n"
                                        "faded indigo bags contain 3 light gold bags, 5 dotted brown bags, 3 dotted cyan bags, 2 drab teal bags.\n"
                                        "clear violet bags contain 1 wavy turquoise bag, 1 vibrant chartreuse bag, 1 dark violet bag, 3 bright bronze bags.\n"
                                        "clear indigo bags contain 1 mirrored tan bag, 4 faded indigo bags.\n"
                                        "bright turquoise bags contain 1 drab teal bag, 4 dull salmon bags, 4 pale olive bags, 2 faded chartreuse bags.\n"
                                        "muted tomato bags contain 1 dark purple bag, 3 striped tan bags.\n"
                                        "posh silver bags contain 4 muted gray bags.\n"
                                        "mirrored olive bags contain 5 bright lavender bags, 2 clear blue bags, 5 dotted crimson bags, 5 pale black bags.\n"
                                        "shiny tomato bags contain 1 mirrored purple bag, 4 posh gold bags, 3 vibrant plum bags.\n"
                                        "striped coral bags contain 5 clear orange bags, 3 muted coral bags, 4 bright green bags, 1 clear chartreuse bag.\n"
                                        "mirrored chartreuse bags contain 4 clear blue bags.\n"
                                        "pale maroon bags contain 1 muted indigo bag.\n"
                                        "striped black bags contain 3 striped gray bags, 1 striped lime bag, 4 bright cyan bags, 4 light orange bags.\n"
                                        "dim maroon bags contain 4 dull cyan bags.\n"
                                        "bright beige bags contain 2 pale fuchsia bags, 5 vibrant beige bags, 1 light lavender bag.\n"
                                        "shiny gray bags contain 2 striped lime bags, 1 pale black bag, 4 wavy tomato bags, 2 vibrant brown bags.\n"
                                        "drab lime bags contain 5 muted bronze bags, 2 posh indigo bags.\n"
                                        "dull gray bags contain 2 dull plum bags, 4 dim white bags, 2 shiny purple bags.\n"
                                        "light olive bags contain 4 clear salmon bags, 1 dim indigo bag.\n"
                                        "vibrant violet bags contain 5 striped tan bags, 1 pale lime bag, 4 posh plum bags, 4 mirrored black bags.\n"
                                        "posh lavender bags contain 4 pale tomato bags.\n"
                                        "plaid coral bags contain 3 mirrored olive bags, 2 muted black bags, 3 light plum bags.\n"
                                        "vibrant blue bags contain 4 mirrored silver bags.\n"
                                        "dim aqua bags contain 5 dim maroon bags.\n"
                                        "wavy bronze bags contain 5 wavy plum bags, 1 bright cyan bag, 2 drab chartreuse bags.\n"
                                        "muted plum bags contain 3 plaid silver bags, 5 faded black bags, 3 drab maroon bags.\n"
                                        "dull turquoise bags contain 4 plaid silver bags.\n"
                                        "plaid blue bags contain 3 plaid purple bags.\n"
                                        "dotted tan bags contain 5 plaid chartreuse bags, 4 dotted coral bags, 4 posh green bags, 1 striped turquoise bag.\n"
                                        "plaid black bags contain 2 drab salmon bags, 5 posh maroon bags.\n"
                                        "light cyan bags contain 2 dotted orange bags, 5 drab green bags, 1 bright lavender bag.\n"
                                        "dull fuchsia bags contain 2 posh red bags, 4 mirrored beige bags, 2 dull salmon bags, 4 striped purple bags.\n"
                                        "dark turquoise bags contain 4 drab tomato bags, 3 dotted chartreuse bags, 5 muted salmon bags, 4 posh magenta bags.\n"
                                        "vibrant silver bags contain 3 dark brown bags, 2 wavy beige bags, 5 dull turquoise bags, 2 drab tan bags.\n"
                                        "dotted tomato bags contain 3 drab tan bags, 2 striped magenta bags, 5 dim violet bags, 4 wavy tomato bags.\n"
                                        "vibrant white bags contain 5 bright crimson bags, 2 mirrored white bags, 5 mirrored indigo bags, 4 wavy teal bags.\n"
                                        "shiny fuchsia bags contain 1 pale lime bag.\n"
                                        "wavy fuchsia bags contain 4 clear cyan bags.\n"
                                        "dotted gray bags contain 3 striped chartreuse bags, 1 dark fuchsia bag.\n"
                                        "bright tomato bags contain 4 wavy orange bags, 2 dotted salmon bags, 1 striped gray bag, 3 pale tomato bags.\n"
                                        "clear chartreuse bags contain 3 clear purple bags.\n"
                                        "dim teal bags contain 3 faded silver bags, 5 vibrant silver bags, 2 wavy fuchsia bags.\n"
                                        "dotted yellow bags contain 5 bright bronze bags, 4 drab teal bags.\n"
                                        "dark indigo bags contain 5 plaid red bags, 5 dim purple bags.\n"
                                        "wavy black bags contain 5 shiny tomato bags, 2 clear gray bags, 4 dim lavender bags, 3 clear blue bags.\n"
                                        "striped green bags contain 3 light crimson bags, 5 mirrored cyan bags, 2 mirrored maroon bags, 2 faded yellow bags.\n"
                                        "dull lime bags contain 3 pale yellow bags.\n"
                                        "faded chartreuse bags contain 2 wavy teal bags, 3 dim olive bags, 2 dull purple bags, 5 vibrant plum bags.\n"
                                        "dark yellow bags contain 2 muted brown bags.\n"
                                        "plaid beige bags contain 3 pale green bags, 3 bright purple bags, 5 faded black bags, 1 drab brown bag.\n"
                                        "faded maroon bags contain 5 drab tomato bags.\n"
                                        "muted silver bags contain 3 striped lime bags, 3 dim orange bags, 3 muted aqua bags, 1 plaid black bag.\n"
                                        "pale violet bags contain 1 mirrored gray bag, 1 dull gold bag, 1 wavy crimson bag, 1 pale magenta bag.\n"
                                        "dim olive bags contain no other bags.\n"
                                        "mirrored bronze bags contain 2 drab white bags.\n"
                                        "dull green bags contain 1 striped silver bag, 2 bright orange bags, 4 dull yellow bags, 4 dotted chartreuse bags.\n"
                                        "bright gray bags contain 1 striped gray bag, 5 dull teal bags, 4 light beige bags, 2 vibrant orange bags.\n"
                                        "light indigo bags contain 1 dim maroon bag, 4 dark indigo bags, 1 dark brown bag, 2 muted beige bags.\n"
                                        "bright magenta bags contain 2 muted lime bags.\n"
                                        "posh crimson bags contain 4 pale indigo bags, 2 faded green bags.\n"
                                        "vibrant plum bags contain 1 posh gray bag, 3 mirrored silver bags, 4 bright brown bags, 2 posh magenta bags.\n"
                                        "wavy lime bags contain 4 wavy black bags, 4 shiny cyan bags, 5 striped aqua bags, 4 plaid gray bags.\n"
                                        "shiny silver bags contain 5 dotted crimson bags, 2 wavy turquoise bags, 1 shiny coral bag.\n"
                                        "dark tan bags contain 5 clear silver bags.\n"
                                        "mirrored brown bags contain 1 dotted brown bag, 2 plaid gray bags, 5 dull tomato bags, 5 clear black bags.\n"
                                        "muted brown bags contain 3 drab magenta bags, 4 plaid aqua bags, 5 dim black bags.\n"
                                        "posh black bags contain 2 bright turquoise bags, 3 mirrored maroon bags, 1 dull white bag.\n"
                                        "wavy aqua bags contain 3 drab green bags, 3 clear magenta bags.\n"
                                        "vibrant chartreuse bags contain 3 muted violet bags.\n"
                                        "wavy silver bags contain 2 muted yellow bags, 4 plaid violet bags.\n"
                                        "shiny salmon bags contain 1 clear yellow bag.\n"
                                        "clear purple bags contain 2 posh green bags, 2 muted gray bags.\n"
                                        "clear cyan bags contain 5 posh gray bags, 5 plaid aqua bags, 1 wavy tomato bag, 1 dim lavender bag.\n"
                                        "wavy coral bags contain 5 dim yellow bags, 3 clear yellow bags.\n"
                                        "wavy green bags contain 4 plaid bronze bags, 4 dull coral bags.\n"
                                        "mirrored gold bags contain 5 bright lavender bags.\n"
                                        "muted fuchsia bags contain 1 dotted purple bag.\n"
                                        "clear maroon bags contain 3 muted gray bags, 2 bright chartreuse bags, 3 dotted gold bags.\n"
                                        "faded salmon bags contain 5 clear green bags.\n"
                                        "striped aqua bags contain 5 pale yellow bags, 1 dotted salmon bag, 1 wavy teal bag, 1 muted yellow bag.\n"
                                        "plaid fuchsia bags contain 2 dim olive bags.\n"
                                        "pale chartreuse bags contain 3 posh magenta bags, 3 mirrored yellow bags.\n"
                                        "shiny beige bags contain 1 mirrored indigo bag.\n"
                                        "posh aqua bags contain 3 pale silver bags, 3 shiny tan bags, 5 striped blue bags, 5 dull salmon bags.\n"
                                        "dull magenta bags contain 5 dotted lime bags, 4 bright plum bags, 5 vibrant turquoise bags.\n"
                                        "posh tomato bags contain 5 shiny tan bags, 1 wavy salmon bag.\n"
                                        "clear red bags contain 5 clear black bags.\n"
                                        "dotted aqua bags contain 1 clear black bag.\n"
                                        "clear olive bags contain 1 plaid gray bag, 3 clear cyan bags.\n"
                                        "dotted green bags contain 3 light red bags.\n"
                                        "clear teal bags contain 5 faded coral bags, 3 wavy plum bags, 5 bright orange bags, 1 clear purple bag.\n"
                                        "plaid orange bags contain 4 pale chartreuse bags, 1 dark silver bag, 2 drab tomato bags.\n"
                                        "pale teal bags contain 1 drab black bag.\n"
                                        "posh chartreuse bags contain 1 dotted gold bag, 4 bright salmon bags.\n"
                                        "pale red bags contain 2 vibrant plum bags, 4 wavy cyan bags, 2 dotted white bags, 1 posh silver bag.\n"
                                        "faded violet bags contain 1 mirrored white bag, 4 muted green bags, 5 mirrored olive bags, 1 dim brown bag.\n"
                                        "faded fuchsia bags contain 2 dark brown bags.\n"
                                        "dotted brown bags contain 4 clear blue bags.\n"
                                        "dark teal bags contain 5 dull cyan bags.\n"
                                        "bright salmon bags contain 2 pale black bags, 5 dotted chartreuse bags, 2 striped chartreuse bags.\n"
                                        "pale blue bags contain 4 shiny gold bags, 2 clear white bags, 1 dotted coral bag.\n"
                                        "dim tan bags contain 3 plaid yellow bags, 5 clear blue bags, 2 clear cyan bags.\n"
                                        "dull beige bags contain 5 shiny maroon bags, 4 mirrored bronze bags, 4 dark plum bags.\n"
                                        "clear magenta bags contain 5 dim bronze bags, 5 wavy olive bags.\n"
                                        "bright black bags contain 2 bright bronze bags, 5 mirrored gold bags, 4 dark yellow bags.\n"
                                        "muted aqua bags contain 2 dark teal bags.\n"
                                        "faded blue bags contain 4 clear salmon bags, 1 light cyan bag, 5 wavy tomato bags.\n"
                                        "dotted indigo bags contain 2 shiny maroon bags, 2 wavy tan bags, 4 dim tomato bags, 1 posh plum bag.\n"
                                        "striped chartreuse bags contain 2 dotted orange bags, 3 bright lavender bags.\n"
                                        "dim indigo bags contain 4 shiny coral bags, 4 mirrored olive bags.\n"
                                        "dotted purple bags contain 4 mirrored white bags, 1 posh yellow bag, 5 drab maroon bags.\n"
                                        "muted chartreuse bags contain 5 bright silver bags, 2 bright brown bags.\n"
                                        "shiny purple bags contain 3 dim maroon bags, 2 mirrored lime bags, 2 light lavender bags, 3 dotted salmon bags.\n"
                                        "faded white bags contain 3 vibrant white bags, 5 muted gray bags.\n"
                                        "muted red bags contain 3 posh coral bags.\n"
                                        "mirrored tan bags contain 1 dotted gold bag, 2 dark coral bags, 3 light purple bags.\n"
                                        "dim blue bags contain 3 dull blue bags, 4 posh plum bags.\n"
                                        "bright indigo bags contain 1 muted white bag, 1 wavy fuchsia bag.\n"
                                        "striped crimson bags contain 3 dotted coral bags.\n"
                                        "light orange bags contain 3 striped chartreuse bags, 4 bright silver bags, 5 clear cyan bags.\n"
                                        "posh yellow bags contain 3 bright brown bags.\n"
                                        "dotted beige bags contain 1 plaid red bag.\n"
                                        "faded aqua bags contain 3 drab tan bags.\n"
                                        "shiny red bags contain 3 striped lime bags, 5 wavy teal bags, 2 muted olive bags, 1 shiny chartreuse bag.\n"
                                        "light tomato bags contain 4 muted green bags.\n"
                                        "bright olive bags contain 4 shiny maroon bags, 1 striped tan bag, 2 drab teal bags, 3 mirrored chartreuse bags.\n"
                                        "mirrored white bags contain 4 vibrant aqua bags, 4 clear blue bags, 4 bright violet bags, 1 muted olive bag.\n"
                                        "posh olive bags contain 2 shiny maroon bags, 3 faded coral bags, 1 dark turquoise bag.\n"
                                        "vibrant lime bags contain 1 light lime bag, 5 bright lime bags, 4 vibrant olive bags.\n"
                                        "striped brown bags contain 3 clear chartreuse bags, 4 drab magenta bags.\n"
                                        "striped lavender bags contain 1 wavy plum bag.\n"
                                        "wavy white bags contain 4 dotted red bags.\n"
                                        "dark bronze bags contain 2 posh green bags, 1 dotted crimson bag, 5 bright lavender bags, 1 shiny coral bag.\n"
                                        "mirrored black bags contain 3 muted salmon bags.\n"
                                        "shiny magenta bags contain 4 dotted orange bags, 4 bright silver bags, 3 posh coral bags.\n"
                                        "light bronze bags contain 3 dotted coral bags.\n"
                                        "mirrored gray bags contain 1 muted olive bag, 1 bright violet bag.\n"
                                        "bright lavender bags contain 1 dull tomato bag, 2 clear blue bags.\n"
                                        "drab yellow bags contain 3 dim tomato bags, 3 striped green bags.\n"
                                        "dark chartreuse bags contain 5 vibrant violet bags, 4 shiny tan bags, 4 dark orange bags, 1 dull tan bag.\n"
                                        "vibrant indigo bags contain 3 mirrored violet bags, 3 light teal bags, 2 dim red bags.\n"
                                        "plaid green bags contain 3 wavy blue bags, 4 wavy yellow bags, 1 dull lavender bag.\n"
                                        "mirrored purple bags contain 5 vibrant silver bags.\n"
                                        "vibrant yellow bags contain 4 plaid brown bags, 3 drab bronze bags, 5 posh bronze bags, 3 mirrored lime bags.\n"
                                        "pale gold bags contain 4 shiny indigo bags, 4 clear maroon bags.\n"
                                        "shiny cyan bags contain 3 dim olive bags.\n"
                                        "dim salmon bags contain 5 faded beige bags, 2 faded orange bags, 2 shiny purple bags.\n"
                                        "dark crimson bags contain 3 dull aqua bags, 1 wavy olive bag, 3 posh plum bags, 3 bright brown bags.\n"
                                        "vibrant gold bags contain 3 wavy gray bags, 4 clear white bags, 1 faded salmon bag, 3 drab aqua bags.\n"
                                        "faded magenta bags contain 5 plaid aqua bags, 4 faded purple bags, 5 wavy bronze bags.\n"
                                        "drab black bags contain 3 pale aqua bags, 2 clear coral bags, 2 mirrored silver bags, 5 dark cyan bags.\n"
                                        "bright green bags contain 1 shiny aqua bag, 5 drab salmon bags, 5 wavy tomato bags, 4 faded beige bags.\n"
                                        "bright aqua bags contain 2 vibrant magenta bags, 3 dim indigo bags, 5 dark fuchsia bags.\n"
                                        "pale olive bags contain 1 dotted brown bag.\n"
                                        "mirrored fuchsia bags contain 1 dull brown bag, 3 light cyan bags.\n"
                                        "mirrored red bags contain 3 plaid lavender bags.\n"
                                        "wavy blue bags contain 5 wavy turquoise bags, 3 light green bags, 4 dim indigo bags, 3 posh coral bags.\n"
                                        "clear silver bags contain 4 plaid gray bags.\n"
                                        "muted white bags contain 2 dotted salmon bags, 4 mirrored white bags, 3 clear cyan bags, 2 muted chartreuse bags.\n"
                                        "dim tomato bags contain 3 drab white bags, 1 posh gray bag, 3 dark cyan bags, 5 posh green bags.\n"
                                        "drab beige bags contain 1 light orange bag, 3 bright salmon bags, 3 pale silver bags.\n"
                                        "clear gold bags contain 2 vibrant white bags, 2 plaid yellow bags.\n"
                                        "vibrant orange bags contain 5 muted chartreuse bags.\n"
                                        "striped tan bags contain 1 wavy gold bag, 3 mirrored black bags, 1 shiny aqua bag, 5 vibrant red bags.\n"
                                        "bright lime bags contain 4 dim indigo bags, 3 dull tomato bags.\n"
                                        "bright red bags contain 5 drab magenta bags, 1 clear salmon bag.\n"
                                        "vibrant green bags contain 4 plaid tomato bags.\n"
                                        "light tan bags contain 5 muted green bags.\n"
                                        "striped white bags contain 1 faded silver bag, 2 vibrant red bags.\n"
                                        "dull violet bags contain 5 dull turquoise bags.\n"
                                        "drab salmon bags contain 3 posh magenta bags, 1 dark teal bag.\n"
                                        "mirrored cyan bags contain 2 dim violet bags, 1 plaid aqua bag, 1 vibrant blue bag, 1 posh magenta bag.\n"
                                        "wavy teal bags contain 1 bright crimson bag, 2 light cyan bags, 4 striped silver bags.\n"
                                        "vibrant purple bags contain 5 shiny magenta bags, 1 dotted orange bag, 2 wavy teal bags.\n"
                                        "faded beige bags contain 1 posh green bag, 5 clear coral bags.\n"
                                        "faded lime bags contain 1 wavy gray bag, 1 light orange bag, 5 clear bronze bags.\n"
                                        "mirrored green bags contain 5 drab bronze bags, 3 muted violet bags, 1 clear blue bag.\n"
                                        "light green bags contain 5 mirrored lavender bags, 3 drab gold bags.\n"
                                        "pale crimson bags contain 3 pale chartreuse bags.\n"
                                        "mirrored aqua bags contain 4 drab plum bags.\n"
                                        "dull crimson bags contain 2 bright white bags, 5 drab olive bags, 5 pale salmon bags.\n"
                                        "dull purple bags contain 1 posh magenta bag, 3 mirrored brown bags.\n"
                                        "bright white bags contain 4 vibrant blue bags, 3 dull brown bags, 4 drab green bags.\n"
                                        "drab indigo bags contain 2 bright salmon bags, 2 muted maroon bags, 2 clear gray bags.\n"
                                        "striped fuchsia bags contain 2 drab gold bags, 4 mirrored white bags, 3 muted black bags, 1 dark teal bag.\n"
                                        "dark tomato bags contain 3 muted fuchsia bags, 1 dotted lavender bag, 4 drab turquoise bags.\n"
                                        "mirrored tomato bags contain 5 dark olive bags, 4 light black bags, 4 dark magenta bags.\n"
                                        "dark plum bags contain 4 wavy yellow bags, 4 shiny salmon bags.\n"
                                        "dark salmon bags contain 1 dim bronze bag, 4 pale indigo bags, 5 dotted chartreuse bags.\n"
                                        "dotted lime bags contain 1 shiny brown bag, 3 faded lavender bags.\n"
                                        "dark red bags contain 3 posh green bags, 1 vibrant bronze bag, 2 dull maroon bags.\n"
                                        "dim lavender bags contain 2 dark turquoise bags.\n"
                                        "striped cyan bags contain 1 clear chartreuse bag.\n"
                                        "dull indigo bags contain 5 shiny brown bags.\n"
                                        "faded green bags contain 1 drab maroon bag.\n"
                                        "drab fuchsia bags contain 2 clear olive bags, 1 bright cyan bag.\n"
                                        "drab gold bags contain 2 dull turquoise bags, 5 dim lavender bags, 4 light teal bags.\n"
                                        "dotted violet bags contain 3 drab tomato bags, 5 dark lavender bags, 4 bright fuchsia bags.\n"
                                        "shiny turquoise bags contain 4 light black bags.\n"
                                        "muted green bags contain 3 vibrant bronze bags, 4 dim olive bags, 2 posh yellow bags, 2 dull cyan bags.\n"
                                        "pale purple bags contain 2 drab yellow bags, 3 bright crimson bags.\n"
                                        "posh fuchsia bags contain 1 dull tan bag, 2 dim orange bags.\n"
                                        "drab teal bags contain 1 dim violet bag, 2 drab green bags, 5 mirrored lavender bags, 2 faded purple bags.\n"
                                        "mirrored teal bags contain 4 vibrant aqua bags, 2 dull turquoise bags, 4 vibrant bronze bags, 3 mirrored olive bags.\n"
                                        "muted violet bags contain 3 wavy chartreuse bags.\n"
                                        "mirrored salmon bags contain 3 clear cyan bags, 5 posh plum bags, 1 shiny coral bag.\n"
                                        "vibrant crimson bags contain 4 dotted chartreuse bags, 2 wavy yellow bags, 3 drab green bags.\n"
                                        "dotted teal bags contain 3 clear black bags, 1 faded blue bag, 1 clear beige bag, 4 striped brown bags.\n"
                                        "posh orange bags contain 1 dim olive bag.\n"
                                        "striped bronze bags contain 1 dull salmon bag, 4 wavy teal bags, 1 pale salmon bag, 2 dim aqua bags.\n"
                                        "clear lime bags contain 1 dim lavender bag, 1 drab magenta bag.\n"
                                        "muted magenta bags contain 1 shiny indigo bag, 4 mirrored cyan bags, 4 shiny cyan bags, 2 posh bronze bags.\n"
                                        "bright chartreuse bags contain 5 drab white bags, 3 dotted purple bags.\n"
                                        "dim magenta bags contain 2 dull turquoise bags, 1 dull coral bag, 3 dark violet bags, 4 muted crimson bags.\n"
                                        "pale cyan bags contain 5 dotted coral bags, 4 drab chartreuse bags, 4 dull plum bags.\n"
                                        "shiny white bags contain 2 drab salmon bags, 3 shiny silver bags.\n"
                                        "faded tan bags contain 4 posh magenta bags, 1 pale teal bag.";

#endif //AOC_2020_DAY_07_INPUT_H
